from app.models import db, Answer

def seed_answers():
  answer_seeds = []

  answer_seeds.append(Answer(poll_id=1, answer='''Right Handed'''))
  answer_seeds.append(Answer(poll_id=1, answer='''Left Handed'''))
  answer_seeds.append(Answer(poll_id=1, answer='''Ambidextrous'''))
  answer_seeds.append(Answer(poll_id=2, answer='''$1,000,000'''))
  answer_seeds.append(Answer(poll_id=2, answer='''$10,000'''))
  answer_seeds.append(Answer(poll_id=3, answer='''It ain't much, but it's honest work'''))
  answer_seeds.append(Answer(poll_id=3, answer='''It ain't honest work, but it's much'''))
  answer_seeds.append(Answer(poll_id=4, answer='''Hulu'''))
  answer_seeds.append(Answer(poll_id=4, answer='''Netflix'''))
  answer_seeds.append(Answer(poll_id=4, answer='''Amazon Prime'''))
  answer_seeds.append(Answer(poll_id=4, answer='''Youtube TV'''))
  answer_seeds.append(Answer(poll_id=5, answer='''I hate it'''))
  answer_seeds.append(Answer(poll_id=5, answer='''I have no opinion'''))
  answer_seeds.append(Answer(poll_id=5, answer='''I love it'''))
  answer_seeds.append(Answer(poll_id=6, answer='''Football'''))
  answer_seeds.append(Answer(poll_id=6, answer='''Hockey'''))
  answer_seeds.append(Answer(poll_id=6, answer='''Baseball'''))
  answer_seeds.append(Answer(poll_id=6, answer='''Basketball'''))
  answer_seeds.append(Answer(poll_id=7, answer='''Smile with teeth'''))
  answer_seeds.append(Answer(poll_id=7, answer='''Smile without teeth'''))
  answer_seeds.append(Answer(poll_id=7, answer='''Serious'''))
  answer_seeds.append(Answer(poll_id=7, answer='''Silly/Other'''))
  answer_seeds.append(Answer(poll_id=8, answer='''Who hasn't?'''))
  answer_seeds.append(Answer(poll_id=8, answer='''I think so'''))
  answer_seeds.append(Answer(poll_id=8, answer='''I'm not sure'''))
  answer_seeds.append(Answer(poll_id=8, answer='''No way!'''))
  answer_seeds.append(Answer(poll_id=9, answer='''Yes'''))
  answer_seeds.append(Answer(poll_id=9, answer='''No, too hot'''))
  answer_seeds.append(Answer(poll_id=9, answer='''Yes, because ghosts'''))
  answer_seeds.append(Answer(poll_id=9, answer='''Sometimes'''))
  answer_seeds.append(Answer(poll_id=10, answer='''Nope'''))
  answer_seeds.append(Answer(poll_id=10, answer='''Yep and it got awkward'''))
  answer_seeds.append(Answer(poll_id=11, answer='''I don't care, I read them'''))
  answer_seeds.append(Answer(poll_id=11, answer='''I don't like them'''))
  answer_seeds.append(Answer(poll_id=11, answer='''I avoid them at all costs'''))
  answer_seeds.append(Answer(poll_id=11, answer='''I don't know'''))
  answer_seeds.append(Answer(poll_id=12, answer='''Yes'''))
  answer_seeds.append(Answer(poll_id=12, answer='''No'''))
  answer_seeds.append(Answer(poll_id=13, answer='''Dangerously In Love'''))
  answer_seeds.append(Answer(poll_id=13, answer='''B'Day'''))
  answer_seeds.append(Answer(poll_id=13, answer='''I am Sasha Fierce'''))
  answer_seeds.append(Answer(poll_id=13, answer='''Other'''))
  answer_seeds.append(Answer(poll_id=14, answer='''have 10 dogs'''))
  answer_seeds.append(Answer(poll_id=14, answer='''have 0 dogs'''))
  answer_seeds.append(Answer(poll_id=15, answer='''Michael'''))
  answer_seeds.append(Answer(poll_id=15, answer='''Jim'''))
  answer_seeds.append(Answer(poll_id=15, answer='''Dwight'''))
  answer_seeds.append(Answer(poll_id=15, answer='''Creed'''))
  answer_seeds.append(Answer(poll_id=15, answer='''Pam'''))
  answer_seeds.append(Answer(poll_id=15, answer='''Angela'''))
  answer_seeds.append(Answer(poll_id=15, answer='''Stanley'''))
  answer_seeds.append(Answer(poll_id=15, answer='''Other'''))


  for answer in answer_seeds:
    db.session.add(answer)

  db.session.commit()


def undo_answers():
  db.session.execute('TRUNCATE answers RESTART IDENTITY CASCADE;')
  db.session.commit()
