"""added poll_id to votes

Revision ID: 7346d0846e20
Revises: b0f8d1f245e3
Create Date: 2021-08-25 15:27:45.938775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7346d0846e20'
down_revision = 'b0f8d1f245e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('poll_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'votes', 'polls', ['poll_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_column('votes', 'poll_id')
    # ### end Alembic commands ###
